# fly.toml app configuration file generated for devmart-backend on 2025-10-30T17:00:05+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'devmart-backend'
primary_region = 'fra'

[build]

[deploy]


[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'off'
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[[mounts]]
source = "data"
destination = "/data"

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1