"""add status to orders table

Revision ID: 514d045f7dd1
Revises: 1f0f31862c92
Create Date: 2025-10-13 13:59:27.343276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '514d045f7dd1'
down_revision = '1f0f31862c92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        batch_op.drop_column('cantidad')
        batch_op.drop_column('precio_unitario')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.drop_column('estado')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('status')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_unitario', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('cantidad', sa.INTEGER(), nullable=False))
        batch_op.drop_column('price')
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
