/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate user and get access token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description User credentials */
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: email
                         * @description User's email address
                         * @example john.doe@example.com
                         */
                        email: string;
                        /**
                         * @description User's password
                         * @example securePassword123
                         */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description User authenticated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description JWT access token for authenticated requests
                             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                             */
                            access_token?: string;
                            /** @example Usuario identificado correctamente */
                            message?: string;
                            user?: {
                                /**
                                 * Format: date-time
                                 * @example 2025-10-20T10:30:00.000000
                                 */
                                created_at?: string;
                                /** @example john.doe@example.com */
                                email?: string;
                                /** @example 1 */
                                id?: number;
                                /**
                                 * @example customer
                                 * @enum {string}
                                 */
                                role?: "customer" | "admin";
                                /** @example john_doe */
                                username?: string;
                            };
                        };
                    };
                };
                /** @description Missing email or password */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Email y contraseña requeridos */
                            error?: string;
                        };
                    };
                };
                /** @description Invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example La contraseña introducida no es correcta */
                            error?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current authenticated user information */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user information */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: date-time
                             * @example 2025-10-20T10:30:00.000000
                             */
                            created_at?: string;
                            /**
                             * Format: email
                             * @example john.doe@example.com
                             */
                            email?: string;
                            /** @example 1 */
                            id?: number;
                            /**
                             * @example customer
                             * @enum {string}
                             */
                            role?: "customer" | "admin";
                            /** @example john_doe */
                            username?: string;
                        };
                    };
                };
                /** @description Authentication required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Missing Authorization Header */
                            msg?: string;
                        };
                    };
                };
                /** @description User not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Usuario no encontrado */
                            error?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description User registration data */
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: email
                         * @description Valid email address
                         * @example john.doe@example.com
                         */
                        email: string;
                        /**
                         * @description Password with at least 6 characters
                         * @example securePassword123
                         */
                        password: string;
                        /**
                         * @description Unique username for the account
                         * @example john_doe
                         */
                        username: string;
                    };
                };
            };
            responses: {
                /** @description User registered successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description JWT access token for authenticated requests
                             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                             */
                            access_token?: string;
                            /** @example Usuario creado exitosamente */
                            message?: string;
                            user?: {
                                /**
                                 * Format: date-time
                                 * @example 2025-10-20T10:30:00.000000
                                 */
                                created_at?: string;
                                /** @example john.doe@example.com */
                                email?: string;
                                /** @example 1 */
                                id?: number;
                                /**
                                 * @example customer
                                 * @enum {string}
                                 */
                                role?: "customer" | "admin";
                                /** @example john_doe */
                                username?: string;
                            };
                        };
                    };
                };
                /** @description Missing required fields */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Faltan campos requeridos */
                            error?: string;
                        };
                    };
                };
                /** @description Username or email already exists */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Este usuario ya existe */
                            error?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all categories */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of all categories */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Productos electrónicos y tecnológicos */
                            description?: string;
                            /** @example 1 */
                            id?: number;
                            /** @example Electrónica */
                            name?: string;
                            /**
                             * @description Número de productos en esta categoría
                             * @example 5
                             */
                            product_count?: number;
                            /** @example electronica */
                            slug?: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        /** Create a new category */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Category data */
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Category description
                         * @example Productos electrónicos y tecnológicos
                         */
                        description?: string;
                        /**
                         * @description Unique category name
                         * @example Electrónica
                         */
                        name: string;
                    };
                };
            };
            responses: {
                /** @description Category created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            category?: {
                                /** @example Productos electrónicos y tecnológicos */
                                description?: string;
                                /** @example 1 */
                                id?: number;
                                /** @example Electrónica */
                                name?: string;
                                /**
                                 * @description Número de productos en esta categoría
                                 * @example 0
                                 */
                                product_count?: number;
                                /** @example electronica */
                                slug?: string;
                            };
                            /** @example Categoria creada correctamente */
                            message?: string;
                        };
                    };
                };
                /** @description Missing required fields */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Es necesario un nombre */
                            error?: string;
                        };
                    };
                };
                /** @description Authentication required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Missing Authorization Header */
                            msg?: string;
                        };
                    };
                };
                /** @description Admin permission required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Requiere permisos de administrador */
                            msg?: string;
                        };
                    };
                };
                /** @description Category already exists */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Esta categoria ya existe */
                            error?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/slug/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific category by slug */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Category unique slug identifier
                     * @example electronica
                     */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Category details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Productos electrónicos y tecnológicos */
                            description?: string;
                            /** @example 1 */
                            id?: number;
                            /** @example Electrónica */
                            name?: string;
                            /**
                             * @description Número de productos en esta categoría
                             * @example 5
                             */
                            product_count?: number;
                            /** @example electronica */
                            slug?: string;
                        };
                    };
                };
                /** @description Category not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Categoría no encontrada */
                            message?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific category by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Category unique identifier
                     * @example 1
                     */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Category details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Productos electrónicos y tecnológicos */
                            description?: string;
                            /** @example 1 */
                            id?: number;
                            /** @example Electrónica */
                            name?: string;
                            /**
                             * @description Número de productos en esta categoría
                             * @example 5
                             */
                            product_count?: number;
                            /** @example electronica */
                            slug?: string;
                        };
                    };
                };
                /** @description Category not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Categoria con id 1 no encontrada */
                            error?: string;
                        };
                    };
                };
            };
        };
        /** Update an existing category */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Category ID to update
                     * @example 1
                     */
                    id: number;
                };
                cookie?: never;
            };
            /** @description Fields to update (all optional) */
            requestBody: {
                content: {
                    "application/json": {
                        /** @example Nueva descripción de la categoría */
                        description?: string;
                        /** @example Tecnología */
                        name?: string;
                    };
                };
            };
            responses: {
                /** @description Category updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            category?: {
                                /** @example Nueva descripción de la categoría */
                                description?: string;
                                /** @example 1 */
                                id?: number;
                                /** @example Tecnología */
                                name?: string;
                                /**
                                 * @description Número de productos en esta categoría
                                 * @example 5
                                 */
                                product_count?: number;
                                /** @example tecnologia */
                                slug?: string;
                            };
                            /** @example Categoria actualizada correctamente */
                            message?: string;
                        };
                    };
                };
                /** @description No data received for update */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example No se recibieron datos para actualizar */
                            error?: string;
                        };
                    };
                };
                /** @description Authentication required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Missing Authorization Header */
                            msg?: string;
                        };
                    };
                };
                /** @description Admin permission required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Requiere permisos de administrador */
                            msg?: string;
                        };
                    };
                };
                /** @description Category not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Categoria con id 1 no encontrada */
                            error?: string;
                        };
                    };
                };
                /** @description Category name already exists */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Esta categoria ya existe */
                            error?: string;
                        };
                    };
                };
            };
        };
        post?: never;
        /** Delete a category */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Category ID to delete
                     * @example 1
                     */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Category deleted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Categoria eliminada correctamente */
                            message?: string;
                        };
                    };
                };
                /** @description Cannot delete category with associated products */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example No se puede eliminar. Hay 5 producto(s) asociados a esta categoria */
                            error?: string;
                        };
                    };
                };
                /** @description Authentication required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Missing Authorization Header */
                            msg?: string;
                        };
                    };
                };
                /** @description Admin permission required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Requiere permisos de administrador */
                            msg?: string;
                        };
                    };
                };
                /** @description Category not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Categoria no encontrada */
                            error?: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{id}/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all products in a specific category */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Category ID
                     * @example 1
                     */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of products in the category */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 1 */
                            category_id?: number;
                            /**
                             * Format: date-time
                             * @example 2025-10-20T10:30:00.000000
                             */
                            created_at?: string;
                            /** @example Laptop de alto rendimiento */
                            description?: string;
                            /** @example 1 */
                            id?: number;
                            /**
                             * Format: uri
                             * @example https://example.com/images/laptop.jpg
                             */
                            image_url?: string;
                            /** @example Laptop HP Pavilion */
                            name?: string;
                            /**
                             * Format: float
                             * @example 899.99
                             */
                            price?: number;
                            /** @example 25 */
                            stock?: number;
                        }[];
                    };
                };
                /** @description Category not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Categoria con id 1 no encontrada */
                            error?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all orders for the authenticated user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of user orders */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: date-time
                             * @example 2025-10-20T10:30:00.000000
                             */
                            created_at?: string;
                            /** @example 1 */
                            id?: number;
                            items?: {
                                /** @example 1 */
                                id?: number;
                                /**
                                 * Format: float
                                 * @example 74.99
                                 */
                                price?: number;
                                /** @example 1 */
                                product_id?: number;
                                /** @example 2 */
                                quantity?: number;
                                /**
                                 * Format: float
                                 * @example 149.98
                                 */
                                subtotal?: number;
                            }[];
                            /**
                             * @example pending
                             * @enum {string}
                             */
                            status?: "pending" | "processing" | "shipped" | "delivered" | "cancelled";
                            /**
                             * Format: float
                             * @example 149.99
                             */
                            total?: number;
                            /** @example 1 */
                            user_id?: number;
                        }[];
                    };
                };
                /** @description Authentication required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Missing Authorization Header */
                            msg?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create a new order */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Order data */
            requestBody: {
                content: {
                    "application/json": {
                        items: {
                            /**
                             * @description ID of the product to order
                             * @example 1
                             */
                            product_id: number;
                            /**
                             * @description Quantity to order
                             * @example 2
                             */
                            quantity: number;
                        }[];
                    };
                };
            };
            responses: {
                /** @description Order created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Pedido creado correctamente */
                            message?: string;
                            order?: {
                                /**
                                 * Format: date-time
                                 * @example 2025-10-20T10:30:00.000000
                                 */
                                created_at?: string;
                                /** @example 1 */
                                id?: number;
                                items?: Record<string, never>[];
                                /** @example pending */
                                status?: string;
                                /**
                                 * Format: float
                                 * @example 149.99
                                 */
                                total?: number;
                                /** @example 1 */
                                user_id?: number;
                            };
                        };
                    };
                };
                /** @description Invalid order data or insufficient stock */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example El pedido debe tener mínimo un producto */
                            error?: string;
                        };
                    };
                };
                /** @description Authentication required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Missing Authorization Header */
                            msg?: string;
                        };
                    };
                };
                /** @description Product not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Producto con id 1 no encontrado */
                            error?: string;
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Error al crear el pedido */
                            error?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific order by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Order ID
                     * @example 1
                     */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Order details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: date-time
                             * @example 2025-10-20T10:30:00.000000
                             */
                            created_at?: string;
                            /** @example 1 */
                            id?: number;
                            items?: {
                                /** @example 1 */
                                id?: number;
                                /**
                                 * Format: float
                                 * @example 74.99
                                 */
                                price?: number;
                                /** @example 1 */
                                product_id?: number;
                                /** @example 2 */
                                quantity?: number;
                                /**
                                 * Format: float
                                 * @example 149.98
                                 */
                                subtotal?: number;
                            }[];
                            /**
                             * @example pending
                             * @enum {string}
                             */
                            status?: "pending" | "processing" | "shipped" | "delivered" | "cancelled";
                            /**
                             * Format: float
                             * @example 149.99
                             */
                            total?: number;
                            /** @example 1 */
                            user_id?: number;
                        };
                    };
                };
                /** @description Authentication required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Missing Authorization Header */
                            msg?: string;
                        };
                    };
                };
                /** @description Permission denied for this order */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example No tienes permiso para este pedido */
                            error?: string;
                        };
                    };
                };
                /** @description Order not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example No se encontro ese pedido */
                            error?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Cancel an order and restore stock */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Order ID to cancel
                     * @example 1
                     */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Order cancelled and stock restored */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Pedido cancelado y stock restaurado */
                            message?: string;
                        };
                    };
                };
                /** @description Cannot cancel order in current status */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example No se puede cancelar un pedido en estado "processing" */
                            error?: string;
                        };
                    };
                };
                /** @description Authentication required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Missing Authorization Header */
                            msg?: string;
                        };
                    };
                };
                /** @description Permission denied for this order */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example No tienes permiso para cancelar este pedido */
                            error?: string;
                        };
                    };
                };
                /** @description Order not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Pedido no encontrado */
                            error?: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update order status */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Order ID to update
                     * @example 1
                     */
                    id: number;
                };
                cookie?: never;
            };
            /** @description New status for the order */
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description New order status
                         * @example processing
                         * @enum {string}
                         */
                        status: "pending" | "processing" | "shipped" | "delivered" | "cancelled";
                    };
                };
            };
            responses: {
                /** @description Order status updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Estado del pedido actualizado */
                            message?: string;
                            order?: {
                                /**
                                 * Format: date-time
                                 * @example 2025-10-20T10:30:00.000000
                                 */
                                created_at?: string;
                                /** @example 1 */
                                id?: number;
                                /** @example processing */
                                status?: string;
                                /**
                                 * Format: float
                                 * @example 149.99
                                 */
                                total?: number;
                                /** @example 1 */
                                user_id?: number;
                            };
                        };
                    };
                };
                /** @description Invalid status or missing data */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example El campo status es requerido */
                            error?: string;
                        };
                    };
                };
                /** @description Authentication required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Missing Authorization Header */
                            msg?: string;
                        };
                    };
                };
                /** @description Order not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Pedido no encontrado */
                            error?: string;
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all products */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of all products */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 1 */
                            category_id?: number;
                            /**
                             * Format: date-time
                             * @example 2025-10-20T10:30:00.000000
                             */
                            created_at?: string;
                            /** @example Laptop de alto rendimiento con 16GB RAM */
                            description?: string;
                            /** @example 1 */
                            id?: number;
                            /**
                             * Format: uri
                             * @example https://example.com/images/laptop.jpg
                             */
                            image_url?: string;
                            /** @example Laptop HP Pavilion */
                            name?: string;
                            /**
                             * Format: float
                             * @example 899.99
                             */
                            price?: number;
                            /** @example 25 */
                            stock?: number;
                        }[];
                    };
                };
            };
        };
        put?: never;
        /** Create a new product */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Product data */
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Category identifier (must exist)
                         * @example 1
                         */
                        category_id?: number;
                        /**
                         * @description Detailed product description
                         * @example Laptop de alto rendimiento con 16GB RAM y SSD 512GB
                         */
                        description?: string;
                        /**
                         * Format: uri
                         * @description URL to product image
                         * @example https://example.com/images/laptop.jpg
                         */
                        image_url?: string;
                        /**
                         * @description Product name
                         * @example Laptop HP Pavilion
                         */
                        name: string;
                        /**
                         * Format: float
                         * @description Product price in dollars
                         * @example 899.99
                         */
                        price: number;
                        /**
                         * @description Available stock quantity
                         * @default 0
                         * @example 25
                         */
                        stock?: number;
                    };
                };
            };
            responses: {
                /** @description Product created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Producto creado correctamente */
                            message?: string;
                            product?: {
                                /** @example 1 */
                                category_id?: number;
                                /**
                                 * Format: date-time
                                 * @example 2025-10-20T10:30:00.000000
                                 */
                                created_at?: string;
                                /** @example Laptop de alto rendimiento con 16GB RAM */
                                description?: string;
                                /** @example 1 */
                                id?: number;
                                /** @example https://example.com/images/laptop.jpg */
                                image_url?: string;
                                /** @example Laptop HP Pavilion */
                                name?: string;
                                /**
                                 * Format: float
                                 * @example 899.99
                                 */
                                price?: number;
                                /** @example 25 */
                                stock?: number;
                            };
                        };
                    };
                };
                /** @description Missing required fields or category not found */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Faltan campos para poder crear el producto */
                            error?: string;
                        };
                    };
                };
                /** @description Authentication required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Missing Authorization Header */
                            msg?: string;
                        };
                    };
                };
                /** @description Admin permission required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Requiere permisos de administrador */
                            msg?: string;
                        };
                    };
                };
                /** @description Category not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Categoria no encontrada */
                            error?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific product by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Unique product identifier
                     * @example 1
                     */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Product details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 1 */
                            category_id?: number;
                            /**
                             * Format: date-time
                             * @example 2025-10-20T10:30:00.000000
                             */
                            created_at?: string;
                            /** @example Laptop de alto rendimiento con 16GB RAM */
                            description?: string;
                            /** @example 1 */
                            id?: number;
                            /**
                             * Format: uri
                             * @example https://example.com/images/laptop.jpg
                             */
                            image_url?: string;
                            /** @example Laptop HP Pavilion */
                            name?: string;
                            /**
                             * Format: float
                             * @example 899.99
                             */
                            price?: number;
                            /** @example 25 */
                            stock?: number;
                        };
                    };
                };
                /** @description Product not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Producto no encontrado */
                            error?: string;
                        };
                    };
                };
            };
        };
        /** Update an existing product */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Product ID to update
                     * @example 1
                     */
                    id: number;
                };
                cookie?: never;
            };
            /** @description Fields to update (all optional) */
            requestBody: {
                content: {
                    "application/json": {
                        /** @example 2 */
                        category_id?: number;
                        /** @example Nueva descripción del producto */
                        description?: string;
                        /**
                         * Format: uri
                         * @example https://example.com/images/laptop-new.jpg
                         */
                        image_url?: string;
                        /** @example Laptop HP Pavilion Updated */
                        name?: string;
                        /**
                         * Format: float
                         * @example 799.99
                         */
                        price?: number;
                        /** @example 30 */
                        stock?: number;
                    };
                };
            };
            responses: {
                /** @description Product updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Producto actualizado correctamente */
                            message?: string;
                            product?: {
                                /** @example 2 */
                                category_id?: number;
                                /**
                                 * Format: date-time
                                 * @example 2025-10-20T10:30:00.000000
                                 */
                                created_at?: string;
                                /** @example Nueva descripción del producto */
                                description?: string;
                                /** @example 1 */
                                id?: number;
                                /** @example https://example.com/images/laptop-new.jpg */
                                image_url?: string;
                                /** @example Laptop HP Pavilion Updated */
                                name?: string;
                                /**
                                 * Format: float
                                 * @example 799.99
                                 */
                                price?: number;
                                /** @example 30 */
                                stock?: number;
                            };
                        };
                    };
                };
                /** @description Authentication required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Missing Authorization Header */
                            msg?: string;
                        };
                    };
                };
                /** @description Admin permission required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Requiere permisos de administrador */
                            msg?: string;
                        };
                    };
                };
                /** @description Product not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example No se encontro el producto con id 1 */
                            error?: string;
                        };
                    };
                };
            };
        };
        post?: never;
        /** Delete a product */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Product ID to delete
                     * @example 1
                     */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Product deleted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Producto eliminado correctamente */
                            message?: string;
                        };
                    };
                };
                /** @description Authentication required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Missing Authorization Header */
                            msg?: string;
                        };
                    };
                };
                /** @description Admin permission required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Requiere permisos de administrador */
                            msg?: string;
                        };
                    };
                };
                /** @description Product not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example No se encontro el producto con id 1 */
                            error?: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
